"""Four supported conversation languages; literal product wording and grammar."""

SENTENCES = {
    "en": {
        "create": ["(log|record) {answer}", "(log|record)"],
        "calendar": ["[show] [my] calendar [for {answer}]"],
        "review": ["review"],
        "confirm": ["confirm", "save"],
        "cancel": ["cancel"],
        "repeat": ["repeat"],
        "more": ["more"],
        "defaults": ["use [the] defaults", "save with [the] default details"],
        "skip": ["skip"],
        "correct": ["(change|correct) {detail} to {answer}"],
        "when": ["(on|at) {answer}"],
    },
    "pl": {
        "create": ["(zapisz|zanotuj) {answer}", "(zapisz|zanotuj)"],
        "calendar": ["[pokaż] kalendarz [na {answer}]"],
        "review": ["podsumowanie", "sprawdź"],
        "confirm": ["potwierdzam", "potwierdź"],
        "cancel": ["anuluj"],
        "repeat": ["powtórz"],
        "more": ["więcej"],
        "defaults": ["użyj domyślnych", "zapisz z domyślnymi szczegółami"],
        "skip": ["pomiń"],
        "correct": ["(zmień|popraw) {detail} na {answer}"],
        "when": ["(dnia|o) {answer}"],
    },
    "de": {
        "create": ["(erfasse|notiere) {answer}", "(erfasse|notiere)"],
        "calendar": ["[zeige] [meinen] Kalender [für {answer}]"],
        "review": ["Zusammenfassung"],
        "confirm": ["bestätigen", "speichern"],
        "cancel": ["abbrechen"],
        "repeat": ["wiederholen"],
        "more": ["mehr"],
        "defaults": ["Standardwerte verwenden", "mit [den] Standardwerten speichern"],
        "skip": ["überspringen"],
        "correct": ["ändere {detail} auf {answer}"],
        "when": ["am {answer}"],
    },
    "fr": {
        "create": ["(enregistre|note) {answer}", "(enregistre|note)"],
        "calendar": ["[affiche] [mon] calendrier [pour {answer}]"],
        "review": ["résumé"],
        "confirm": ["confirmer"],
        "cancel": ["annuler"],
        "repeat": ["répéter"],
        "more": ["plus"],
        "defaults": ["utiliser les valeurs par défaut", "enregistrer avec les valeurs par défaut"],
        "skip": ["passer"],
        "correct": ["change {detail} en {answer}"],
        "when": ["le {answer}"],
    },
}

WORDS = {
    "en": {
        "tracker": "What would you like to record?",
        "subject": "Who is this for?",
        "boolean": "Yes / no.",
        "optional": "You can say: skip.",
        "defaults": "Use these default details, then review before saving?",
        "today": "today",
        "days": {"today": 0, "yesterday": -1, "tomorrow": 1},
        "booleans": {"yes": True, "no": False},
        "numbers": "zero one two three four five six seven eight nine ten",
    },
    "pl": {
        "tracker": "Co zapisać?",
        "subject": "Dla kogo?",
        "boolean": "Tak / nie.",
        "optional": "Możesz powiedzieć: pomiń.",
        "defaults": "Użyć tych domyślnych szczegółów, a następnie sprawdzić przed zapisem?",
        "today": "dzisiaj",
        "days": {"dzisiaj": 0, "dziś": 0, "wczoraj": -1, "jutro": 1},
        "booleans": {"tak": True, "nie": False},
        "numbers": "zero jeden dwa trzy cztery pięć sześć siedem osiem dziewięć dziesięć",
    },
    "de": {
        "tracker": "Was möchtest du erfassen?",
        "subject": "Für wen?",
        "boolean": "Ja / nein.",
        "optional": "Du kannst sagen: überspringen.",
        "defaults": "Diese Standardwerte verwenden und vor dem Speichern prüfen?",
        "today": "heute",
        "days": {"heute": 0, "gestern": -1, "morgen": 1},
        "booleans": {"ja": True, "nein": False},
        "numbers": "null eins zwei drei vier fünf sechs sieben acht neun zehn",
    },
    "fr": {
        "tracker": "Que souhaites-tu enregistrer ?",
        "subject": "Pour qui ?",
        "boolean": "Oui / non.",
        "optional": "Tu peux dire : passer.",
        "defaults": "Utiliser ces valeurs par défaut, puis vérifier avant de sauvegarder ?",
        "today": "aujourd'hui",
        "days": {"aujourd'hui": 0, "aujourd’hui": 0, "hier": -1, "demain": 1},
        "booleans": {"oui": True, "non": False},
        "numbers": "zéro un deux trois quatre cinq six sept huit neuf dix",
    },
}
